
import tkinter as tk


class Show:
    def __init__(self):
        top = tk.Tk()

        top.geometry("600x1000")
        
        top.resizable(0, 0)
        top.title("Check The Info")
        top.configure(background="#d9d9d9")

        photo = tk.PhotoImage(file=r"C:\Users\GIGABYTE\Desktop\Project\Faces\6\2.png")

        self.ID = tk.Label(top,font="-family {Product Sans} -size 18 -weight normal")
        self.ID.place(relx=0.193, rely=0.288, height=71, width=124)
        self.ID.configure(activebackground="#f9f9f9")
        self.ID.configure(activeforeground="black")
        self.ID.configure(background="#d9d9d9")
        self.ID.configure(cursor="fleur")
        self.ID.configure(disabledforeground="#a3a3a3")
        self.ID.configure(foreground="#000000")
        self.ID.configure(highlightbackground="#d9d9d9")
        self.ID.configure(highlightcolor="black")
        self.ID.configure(text='''ID : ''')

        self.IMAGE = tk.Label(top,image=photo)
        self.IMAGE.place(relx=0.3, rely=0.038, height=201, width=224)
        self.IMAGE.configure(activebackground="#f9f9f9")
        self.IMAGE.configure(activeforeground="black")
        self.IMAGE.configure(background="#d9d9d9")
        self.IMAGE.configure(disabledforeground="#a3a3a3")
        self.IMAGE.configure(foreground="#000000")
        self.IMAGE.configure(highlightbackground="#d9d9d9")
        self.IMAGE.configure(highlightcolor="black")
        self.IMAGE.configure(text='''IMAGE''')

        self.NAME = tk.Label(top,font="-family {Product Sans} -size 18 -weight normal")
        self.NAME.place(relx=0.2, rely=0.35, height=71, width=114)
        self.NAME.configure(activebackground="#f9f9f9")
        self.NAME.configure(activeforeground="black")
        self.NAME.configure(background="#d9d9d9")
        self.NAME.configure(disabledforeground="#a3a3a3")
        self.NAME.configure(foreground="#000000")
        self.NAME.configure(highlightbackground="#d9d9d9")
        self.NAME.configure(highlightcolor="black")
        self.NAME.configure(text='''Name :''')

        self.AGE = tk.Label(top,font="-family {Product Sans} -size 18 -weight normal")
        self.AGE.place(relx=0.0, rely=0.463, height=61, width=144)
        self.AGE.configure(activebackground="#f9f9f9")
        self.AGE.configure(activeforeground="black")
        self.AGE.configure(background="#d9d9d9")
        self.AGE.configure(disabledforeground="#a3a3a3")
        self.AGE.configure(foreground="#000000")
        self.AGE.configure(highlightbackground="#d9d9d9")
        self.AGE.configure(highlightcolor="black")
        self.AGE.configure(text='''Age :''')

        self.GENDER = tk.Label(top,font="-family {Product Sans} -size 18 -weight normal")
        self.GENDER.place(relx=0.017, rely=0.55, height=71, width=124)
        self.GENDER.configure(activebackground="#f9f9f9")
        self.GENDER.configure(activeforeground="black")
        self.GENDER.configure(background="#d9d9d9")
        self.GENDER.configure(cursor="fleur")
        self.GENDER.configure(disabledforeground="#a3a3a3")
        self.GENDER.configure(foreground="#000000")
        self.GENDER.configure(highlightbackground="#d9d9d9")
        self.GENDER.configure(highlightcolor="black")
        self.GENDER.configure(text='''Gender : ''')

        self.POST = tk.Label(top,font="-family {Product Sans} -size 18 -weight normal")
        self.POST.place(relx=0.012, rely=0.638, height=81, width=134)
        self.POST.configure(activebackground="#f9f9f9")
        self.POST.configure(activeforeground="black")
        self.POST.configure(background="#d9d9d9")
        self.POST.configure(disabledforeground="#a3a3a3")
        self.POST.configure(foreground="#000000")
        self.POST.configure(highlightbackground="#d9d9d9")
        self.POST.configure(highlightcolor="black")
        self.POST.configure(text='''Post : ''')

        self.CONTACT = tk.Label(top,font="-family {Product Sans} -size 18 -weight normal")
        self.CONTACT.place(relx=0.022, rely=0.75, height=71, width=124)
        self.CONTACT.configure(activebackground="#f9f9f9")
        self.CONTACT.configure(activeforeground="black")
        self.CONTACT.configure(background="#d9d9d9")
        self.CONTACT.configure(disabledforeground="#a3a3a3")
        self.CONTACT.configure(foreground="#000000")
        self.CONTACT.configure(highlightbackground="#d9d9d9")
        self.CONTACT.configure(highlightcolor="black")
        self.CONTACT.configure(text='''Contact : ''')

        self.ADDRESS = tk.Label(top,font="-family {Product Sans} -size 18 -weight normal")
        self.ADDRESS.place(relx=-0.057, rely=0.838, height=81, width=224)
        self.ADDRESS.configure(activebackground="#f9f9f9")
        self.ADDRESS.configure(activeforeground="black")
        self.ADDRESS.configure(background="#d9d9d9")
        self.ADDRESS.configure(disabledforeground="#a3a3a3")
        self.ADDRESS.configure(foreground="#000000")
        self.ADDRESS.configure(highlightbackground="#d9d9d9")
        self.ADDRESS.configure(highlightcolor="black")
        self.ADDRESS.configure(text='''Address : ''')

        self.IDd = tk.Label(top,font="-family {Product Sans} -size 28 -weight normal")
        self.IDd.place(relx=0.383, rely=0.309, height=41, width=124)
        self.IDd.configure(activebackground="#f9f9f9")
        self.IDd.configure(activeforeground="black")
        self.IDd.configure(background="#d9d9d9")
        self.IDd.configure(disabledforeground="#a3a3a3")
        self.IDd.configure(foreground="#000000")
        self.IDd.configure(highlightbackground="#d9d9d9")
        self.IDd.configure(highlightcolor="black")
        self.IDd.configure(text="19")

        self.NAMEd = tk.Label(top,font="-family {Product Sans} -size 28 -weight normal",justify='left')
        self.NAMEd.place(relx=0.4, rely=0.36, height=50, width=300)
        self.NAMEd.configure(activebackground="#f9f9f9")
        self.NAMEd.configure(activeforeground="black")
        self.NAMEd.configure(background="#d9d9d9")
        self.NAMEd.configure(disabledforeground="#a3a3a3")
        self.NAMEd.configure(foreground="#000000")
        self.NAMEd.configure(highlightbackground="#d9d9d9")
        self.NAMEd.configure(highlightcolor="black")
        self.NAMEd.configure(text="AAYUSH SHAH")

        self.AGEd = tk.Label(top,font="-family {Product Sans} -size 28 -weight normal",justify='left')
        self.AGEd.place(relx=0.2, rely=0.45, height=71, width=300)
        self.AGEd.configure(activebackground="#f9f9f9")
        self.AGEd.configure(activeforeground="black")
        self.AGEd.configure(background="#d9d9d9")
        self.AGEd.configure(disabledforeground="#a3a3a3")
        self.AGEd.configure(foreground="#000000")
        self.AGEd.configure(highlightbackground="#d9d9d9")
        self.AGEd.configure(highlightcolor="black")
        self.AGEd.configure(text="AAYUSH SHAH")

        self.GENDERd = tk.Label(top,font="-family {Product Sans} -size 28 -weight normal",justify='left')
        self.GENDERd.place(relx=0.2, rely=0.55, height=71, width=300)
        self.GENDERd.configure(activebackground="#f9f9f9")
        self.GENDERd.configure(activeforeground="black")
        self.GENDERd.configure(background="#d9d9d9")
        self.GENDERd.configure(disabledforeground="#a3a3a3")
        self.GENDERd.configure(foreground="#000000")
        self.GENDERd.configure(highlightbackground="#d9d9d9")
        self.GENDERd.configure(highlightcolor="black")
        self.GENDERd.configure(text="AAYUSH SHAH")

        self.POSTd = tk.Label(top,font="-family {Product Sans} -size 28 -weight normal",justify='left')
        self.POSTd.place(relx=0.2, rely=0.643, height=71, width=300)
        self.POSTd.configure(activebackground="#f9f9f9")
        self.POSTd.configure(activeforeground="black")
        self.POSTd.configure(background="#d9d9d9")
        self.POSTd.configure(disabledforeground="#a3a3a3")
        self.POSTd.configure(foreground="#000000")
        self.POSTd.configure(highlightbackground="#d9d9d9")
        self.POSTd.configure(highlightcolor="black")
        self.POSTd.configure(text="AAYUSH SHAH")

        self.CONTACTd = tk.Label(top,font="-family {Product Sans} -size 28 -weight normal",justify='left')
        self.CONTACTd.place(relx=0.2, rely=0.763, height=71, width=300)
        self.CONTACTd.configure(activebackground="#f9f9f9")
        self.CONTACTd.configure(activeforeground="black")
        self.CONTACTd.configure(background="#d9d9d9")
        self.CONTACTd.configure(disabledforeground="#a3a3a3")
        self.CONTACTd.configure(foreground="#000000")
        self.CONTACTd.configure(highlightbackground="#d9d9d9")
        self.CONTACTd.configure(highlightcolor="black")
        self.CONTACTd.configure(text="AAYUSH SHAH")

        self.ADDRESSd = tk.Label(top,font="-family {Product Sans} -size 28 -weight normal",justify='left')
        self.ADDRESSd.place(relx=0.2, rely=0.838, height=81, width=300)
        self.ADDRESSd.configure(activebackground="#f9f9f9")
        self.ADDRESSd.configure(activeforeground="black")
        self.ADDRESSd.configure(background="#d9d9d9")
        self.ADDRESSd.configure(disabledforeground="#a3a3a3")
        self.ADDRESSd.configure(foreground="#000000")
        self.ADDRESSd.configure(highlightbackground="#d9d9d9")
        self.ADDRESSd.configure(highlightcolor="black")
        self.ADDRESSd.configure(text="AAYUSH SHAH")

        self.ADDMOREbtn = tk.Button(top,text = "ADD ONE MORE",font="-family {Product Sans} -size 12 -weight bold",fg="white",bg="#800040")
        self.ADDMOREbtn.place(relx=0.15,rely=0.93,height=50,width=150)

        self.TRAINbtn = tk.Button(top,text = "TRAIN ALL FACES",font="-family {Product Sans} -size 12 -weight bold",fg="white",bg="#700100")
        self.TRAINbtn.place(relx=0.55,rely=0.93,height=50,width=150)

        #Edit Baki chhe...
        top.mainloop()

Show()





